# Generated by Django 5.0.7 on 2024-09-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('owner', 'Restaurant Owner'), ('deliverypartner', 'Delivery Partner')], default='consumer', max_length=100),
        ),
    ]
