# Generated by Django 5.0.7 on 2024-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlocation',
            name='location',
            field=models.TextField(default=None),
        ),
    ]
