# Generated by Django 5.1 on 2024-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='latitude',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='customerlocation',
            name='longitude',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
