# Generated by Django 5.1 on 2024-10-16 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customerlocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default=None, max_length=200)),
                ('longitude', models.CharField(default=None, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
