# Generated by Django 5.0.7 on 2024-09-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_stock',
        ),
    ]
