# Generated by Django 5.0.7 on 2024-09-03 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_food_food_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantinventory',
            name='restaurant_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='onwner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
