# Generated by Django 5.1 on 2024-10-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_order_delivery_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ontheway', 'On the Way'), ('delivered', 'Delivered'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('no_delivery_partner', 'No Delivery Partner Found')], default='pending', max_length=120),
        ),
    ]
